(:window
  :name "gamelauncher"
  :stacking "above"
  :exclusive true
  :monitor 0
  :geometry (:width "30%" :height "60%" :x "35%" :y "20%")
  :class "gamelauncher"
  (:box
    :class "bg"
    :orientation "v"
    (:button :onclick "exec:steam" "ğŸ® Steam")
    (:button :onclick "exec:lutris" "ğŸ•¹ï¸ Lutris")
    (:button :onclick "exec:heroic" "ğŸ¯ Heroic")
    (:button :onclick "exec:spotify" "ğŸµ Spotify")
    (:button :onclick "exec:eww close gamelauncher" "âŒ Close")
  )
)
