(:window
  :name "powermenu"
  :stacking "above"
  :exclusive true
  :monitor 0
  :geometry (:width "20%" :height "60%" :x "60%" :y "20%")
  :class "powermenu"
  (:box
    :class "bg"
    :orientation "v"
    (:button :onclick "exec:hyprlock" "ğŸ”’ Lock")
    (:button :onclick "exec:systemctl suspend" "ğŸŒ™ Sleep")
    (:button :onclick "exec:rofi -show power-menu" "ğŸ›‘ Logout")
    (:button :onclick "exec:sudo reboot" "ğŸ” Reboot")
    (:button :onclick "exec:sudo shutdown now" "â›” Shutdown")
    (:button :onclick "exec:eww close powermenu" "âŒ Close")
  )
)
